[build]
  base = "foodwaste"
  command = "npm run build:client"
  publish = "dist/spa"
  functions = "netlify/functions"

[build.environment]
  PNPM_FLAGS = "--no-frozen-lockfile"
  NODE_VERSION = "22.21.1"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"